### ISSUE TITLE
cge 检测到游戏分辨率改变时通知 cgc 重启视频播放

### ISSUE THREAD

**Issue by UMU618** [ksyun-kenc/liuguang#13]
理由：强行继续则 cgc 可能会看到一个花屏。

**Comment by UMU618** [comment]
已经改进，请下载最新版（主要是 cgc）。

https://ks3-cn-beijing.ksyun.com/liuguang/regame_v0.3.zip

**Comment by SerkaFox** [comment]
Thank you, but H264 not working with amf I think.
