### ISSUE TITLE
可能有bug

### ISSUE THREAD

**Issue by skiluo** [ksyun-kenc/liuguang#16]
这个地方在多个session的时候，queue 应该存在线程安全问题吧
https://github.com/ksyun-kenc/liuguang/blob/732bf07bf609b6fafe667eb59a25b40e5650b13e/src/cge/cge/ws_server.cpp#L219

**Comment by UMU618** [comment]
前几天 github 太慢回复不了。@skiluo 您少看了代码，有加锁。
