### ISSUE TITLE
大概什么时候开源客户端呢

### ISSUE THREAD

**Issue by andy136240860** [ksyun-kenc/liuguang#2]
RT，想本地试一下看看效果，但是没有客户端，能告知下大概时间么

**Comment by UMU618** [comment]
目前有一个测试版客户端您可以先用 exe，这个版本由于一些历史原因和开源协议冲突不方便开源，所以我们重新开发一个社区版客户端，于 2021 年元旦之后开始开发，大约春节期间可以看到。

**Comment by UMU618** [comment]
cgc will be open source when Regame have 2000 stars.

**Comment by andy136240860** [comment]
那我赶紧帮你推广推广集星， 哈哈哈
