### ISSUE TITLE
Remote Desktop Support

### ISSUE THREAD

**Issue by IDerr** [ksyun-kenc/liuguang#25]
Hello,

Thanks for this great product ! 
I was wondering if this product, will support displaying desktops instead of games on the opensource side, it'll be a good fit for people working from home, and accessing my windows PC easily from a small computer

Thanks a lot

**Comment by UMU618** [comment]
@IDerr You can try to hook `dwm.exe`.

I think `Microsoft Remote Desktop` is good enough, so I will just focus on games.

**Comment by IDerr** [comment]
ok :D thanks for the answer 👍

**Comment by UMU618** [comment]
Support desktop mode now.
