### ISSUE TITLE
Need handling device reset in cgh

### ISSUE THREAD

**Issue by ouchuan** [ksyun-kenc/liuguang#26]
In cgh, IDXGISwapChain1::Present1 will be replace by MyPresent1, and it keep the pointer to device and use it to capture picture from game.
but, if the injected application meet device hung, the device will be reset.
In such case, the app will crash in next present1 call since MyPresent1 try to access the device which was reset.

The attached code can simulate GPU reset. If you use cgi to inject hooks, the app will crash at the third [IDXGISwapChain1::Present1].(you may have to try several times since this code cannot 100% cause GPU reset)
[main.zip](https://github.com/ksyun-kenc/liuguang/files/7838786/main.zip)

**Comment by ouchuan** [comment]
The test code was inspired by libAngle
https://github.com/google/angle/blob/main/src/tests/egl_tests/EGLRobustnessTest.cpp

**Comment by UMU618** [comment]
Will fix in #28

**Comment by sandmanhome** [comment]
> In cgh, IDXGISwapChain1::Present1 will be replace by MyPresent1, and it keep the pointer to device and use it to capture picture from game. but, if the injected application meet device hung, the device will be reset. In such case, the app will crash in next present1 call since MyPresent1 try to access the device which was reset.
> 
> The attached code can simulate GPU reset. If you use cgi to inject hooks, the app will crash at the third [IDXGISwapChain1::Present1].(you may have to try several times since this code cannot 100% cause GPU reset) [main.zip](https://github.com/ksyun-kenc/liuguang/files/7838786/main.zip)


- The attached code will  trigger an DXGI_ERROR_DEVICE_HUNG error, neither the app nor cgc crash.

- `dxcap.exe -forcetdr` can trigger an DXGI_ERROR_DEVICE_REMOVED error then you can test your error handling code ([testing-device-removed-handling](https://docs.microsoft.com/en-us/windows/uwp/gaming/handling-device-lost-scenarios#testing-device-removed-handling)).

- using `dxcap.exe -forcetdr` to manually trigger an DXGI_ERROR_DEVICE_HUNG error, cgc run crashed, but the app works fine. **cgc may be missing Device Removed Handling**.

**Comment by UMU618** [comment]
@sandmanhome `cgc` is cross-platform application, so it doesn't call DX directly. Maybe you could try the SDL examples, if you reproduce the error, you may submit issue to <https://github.com/libsdl-org/SDL/issues>.

**Comment by ouchuan** [comment]
@sandmanhome fix the test code, can you try this again?

test step:
1、run the test code by cgi
.\cgi -d true -e tdrtest.exe -i tdrtest.exe --lx64 .\captureyuv.dll
2、wait until cgc responded
3、wait until tdr triggered(or use dxcap)

the video shows how i reproduce the issue

https://user-images.githubusercontent.com/15075112/159207888-37075c84-ef17-49a3-9b6f-cee3e21f27fd.mp4
[main.zip](https://github.com/ksyun-kenc/liuguang/files/8313241/main.zip)
