### ISSUE TITLE
UserManager may crash `cge`

### ISSUE THREAD

**Issue by UMU618** [ksyun-kenc/liuguang#30]
Most of functions in class UserManager are NOT noexcept. If they throw, `cge` crash.

**Comment by sandmanhome** [comment]
- cgc disconnected cge is able to reproduce the exception.

- calling boost::asio::steady_timer::cancel in case of an error in the handler ([RetryNextConnection](https://github.com/ksyun-kenc/liuguang/blob/78f946a32a156f7e9e3d9729f997757b25912754/src/cge/cge/user_manager.cpp#L179)、[InvokeNextKeepAlive](https://github.com/ksyun-kenc/liuguang/blob/78f946a32a156f7e9e3d9729f997757b25912754/src/cge/cge/user_manager.cpp#L168)) may trigger an exception. 

- it is not necessary to call the cancel function in the timer callback, **remove it to fix it**!
