### ISSUE TITLE
为什么不考虑用OBS推流？

### ISSUE THREAD

**Issue by manyhelp** [ksyun-kenc/liuguang#32]
请问为什么不考虑用obs推流？ 
一个服务器，多个显卡，虚拟化多台电脑。（目前国内的厂家大多数都是这种方案）
单个虚拟机直接推流到客户端电脑（或者其他设备，机顶盒、安卓电视）

cgi
一个命令行工具，用于把 Hook DLL 注入到游戏进程。（很多游戏或者软件都有安全限制）

**Comment by UMU618** [comment]
考虑了，技术上是差不多的东西。但是 OBS 没有鎏光快。

安全限制不要太操心，那些限制很厉害的，本身就不适合云化。这还涉及版权问题，不是技术问题。为了回避游戏版权问题，可以改用云桌面的方案。

**Comment by fingera** [comment]
年轻人你可能不知道，鎏光在低延迟这条路上已经走太远了，基本把所有商业化的云游戏能做的都做完了。代码也看着赏心悦目

**Comment by UMU618** [comment]
接龙我会。（怎么感觉这是我梦游时说的？）

年轻人你可能不知道，鎏光在低延迟这条路上已经走得太远，基本把所有商业化的云游戏能做的都做完了。代码也很好编译和维护。
