### ISSUE TITLE
Why doesn't the cgc keyboard work?

### ISSUE THREAD

**Issue by rv64m** [ksyun-kenc/liuguang#34]
I start cgc on macos, the game screen shows up, but the keyboard doesn't work.

- OS: windows 11, test mode turned on, Cloud Gaming Virtual Device installed
- Successfully compiled cgh and injected the dll into cyberpunk 2077
- Successfully run cge and user-service

cge start command:

```shell
./cge --hardware-encoder=nvenc --keyboard-replay=cgvhid --gamepad-replay=vigem
```

and cgc
```shell
 ./cgc-u UMU --verification-code 123456 --view-only=0
```

**Comment by nivalume** [comment]
cc @UMU618

**Comment by UMU618** [comment]
1. Run debug version of cge with `--log-level=trace` to see if the kb mesage arrived.
2. Should ensure the window of cyberpunk 2077 is active to receive kb message.
