### ISSUE TITLE
engine.cpp raise string type error

### ISSUE THREAD

**Issue by xiasun** [ksyun-kenc/liuguang#39]
**Commid hash:** 3f9fa851a1ba747754f85d6553697fa6c8ecf1d0

**Source file:** engine.cpp

**Error message:** Severity	Code	Description	Project	File	Line	Suppression State
Error	C2679	binary '=': no operator found which takes a right-hand operand of type 'boost::urls::string_view' (or there is no acceptable conversion)	cge	D:\Projects\CloudXR\LiuGuang\src\cge\cge\engine.cpp	84

**Source code:**	

```
user_service_target_ = u.encoded_path();
```
should the above line be changed to something like this?
```
user_service_target_ = std::string(u.encoded_path().data(), u.encoded_path().size());
```

**Comment by UMU618** [comment]
Use Boost 1.79.0

**Comment by xiasun** [comment]
fine
