### ISSUE TITLE
请教D3D12支持的实现

### ISSUE THREAD

**Issue by xiasun** [ksyun-kenc/liuguang#46]
您好，

我想尝试支持d3d12的游戏，我看到cge中的d3d接口调的都是d3d11的，cgh中有d3d11on12的部分实现，但看起来好像不是为了支持注入到d3d12的游戏？
readme有提到支持d3d9/11/12，想请问下对d3d12游戏的支持，是在哪里实现的？

感谢！

**Comment by xiasun** [comment]
@UMU618 请求指教，感谢！

**Comment by UMU618** [comment]
就是通过 d3d11on12 实现的。如果不想用 d3d11on12，而是直接 hook d3d12，那鎏光没开源这部分，等新负责人来了再问他。

**Comment by xiasun** [comment]
了解了，感谢。
