### ISSUE TITLE
AbsoluteMouseMove和RelativeMouseMove的单位是什么？

### ISSUE THREAD

**Issue by xiasun** [ksyun-kenc/liuguang#48]
Hi all,

我尝试在cgvhid_client工程中测试鼠标交互

屏幕分辨率是1920x1080，有在这里设置
https://github.com/ksyun-kenc/liuguang/blob/cbda913c882951992fe403b1647363f3dc91f7b6/src/cge/cgvhid_test/cgvhid_test.cpp#L282

仅使用AbsoluteMouseMove设置鼠标位置时，设置坐标(1920,0)鼠标仅出现在屏幕左上角，而非预期的屏幕最右侧
https://github.com/ksyun-kenc/liuguang/blob/cbda913c882951992fe403b1647363f3dc91f7b6/src/cge/cgvhid_test/cgvhid_test.cpp#L144

仅使用RelativeMouseMove设置鼠标位置时，鼠标初始位置放在屏幕最左侧，移动(1000,0)后就已经到达了屏幕最右侧，预期应移动1920才能到达
https://github.com/ksyun-kenc/liuguang/blob/cbda913c882951992fe403b1647363f3dc91f7b6/src/cge/cgvhid_test/cgvhid_test.cpp#L162

请问鼠标移动的这两个函数对应的单位是什么呢？

感谢

**Comment by xiasun** [comment]
@UMU618 请问您了解么？

**Comment by UMU618** [comment]
AbsoluteMouseMove(1000, 1000) 这如果是跑到屏幕右下角，不是说明是千分？

**Comment by xiasun** [comment]
我最后本地反复尝试的结果是，AbsoluteMouseMove(1920 * 17, 1080 * 30)最终能位于屏幕的右下角，不太这两个系数的来源

**Comment by UMU618** [comment]
推理一下，最大的 int16_t 是 0x7fff（32767）。

**Comment by xiasun** [comment]
感谢感谢，没注意到是int16，现在改成把宽高归一化到int16_t的范围内，移动就很平滑了！
